### ISSUE TITLE
Use as a library vs CLI?

### ISSUE THREAD

**Issue by krsyoung** [koppen/csv_query#3]
Hi @koppen, great project!  I was thinking of including this in a project as a library (vs CLI).   Initial thoughts would be to build-up the `options` hash and then call `CsvQuery::Query.new(csv_data, outputter, options).run`

It looks like I might need to make a variation of the outputter as well so that it returns an array vs printing to stdout.

Thoughts on the approach or other ideas?

**Comment by koppen** [comment]
I guess that approach would work. Especially the part with a custom outputter that simply returns its "output" is cool.

@IntractableQuery is also using this as library rather than a standalone tool, I believe, so there might be good reasons to actually rework the code to make this use case easier/simpler. It's just not something I had considered.

**Comment by krsyoung** [comment]
Cool, thanks @koppen, will hack around with it and come back here if I come up with something pretty :-)  Thanks again!
